### PR TITLE
fix: allow audience and scope to be supplied during initialization

### LINKED ISSUE #271: Web: Missing Refresh Token
### Checklist

- [X] The issue can be reproduced in the [auth0_flutter sample app](https://github.com/auth0-samples/auth0-flutter-samples/tree/main/sample) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-flutter/tree/main/auth0_flutter#readme), [Examples](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-flutter/blob/main/auth0_flutter/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://pub.dev/documentation/auth0_flutter/latest/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-flutter/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I found a problem using refreshtokens and localstorage on web implementation. I not 100% sure if im doing it wrong or if this is a bug, because i cannot give an audience for onLoad function.

### Reproduction

This is the inital conf:

```
      final credentials = await auth0Web.onLoad(
        cacheLocation: CacheLocation.localStorage,
        useRefreshTokens: true,
      );
```
and here the Login happens:
```
final credentials = await auth0Web.loginWithPopup(
        audience: Config.auth0Audience,
      );
```
The data is saved in LocalStorage as expected with audience information.

When I rerun the application i get the following WebException from onLoad():

[ERROR] | 11:26:38 466ms | Missing Refresh Token (audience: '', scope: 'openid profile email offline_access')

So there is an error that we do not have an audience here. Where can i config the audience in onLoad? Is this an misusing on my side?

### Additional context

_No response_

### auth0_flutter version

1.2.0

### Flutter version

3.10.2

### Platform

Web

### Platform version(s)

1.2.0

### PR DESCRIPTION
**Pull request by stevehobbsdev**
- [ ] All new/changed/fixed functionality is covered by tests (or N/A)
- [X] I have added documentation for all new/changed functionality (or N/A)

### 📋 Changes

This PR adds the ability to specify `audience` and `scopes` to `onLoad()`. This fixes an issue in a specific scenario when using both `useRefreshTokens` and `cacheLocation: CacheLocation.localStorage` and logging in with `audience` causes the refresh token to be missing during initialization.

This happens because `audience` (and `scopes`) are used as part of the cache key when looking up the refresh token internally but until now a developer had no way to specify those values.

### 📎 References

Fixes #271 

### 🎯 Testing

Tested manually by supplying `audience` and `scope` to `onLoad()`, logging in, and observing data coming through local storage and to `/authorize`.

### CODE REVIEW

File: auth0_flutter/lib/src/web/js_interop.dart [hunk 1]
```diff
@@ -79,6 +79,7 @@ class Auth0ClientOptions {
       {required final Auth0ClientInfo clientInfo,
       required final String domain,
       required final String clientId,
+      final String? audience,
```
Comment (Widcket) [inline auth0_flutter/lib/src/web/js_interop.dart:82]: Is this needed here since we're adding `authorizationParams` below?

**Review by Widcket — APPROVED** [review]
